# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settingss
title: Joe Laskowski
subtitle: thebiglaskowski
email: joe.laskowski79@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  lover of linux and code. snob of coffee and beer. fanatic of mma.
copyright: Â© 2016. all rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joelaskowski.me" # the base hostname & protocol for your site
twitter_username: thebiglaskowski
github_username:  thebiglaskowski
linkedin_username: thebiglaskowski
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Build settings
markdown: kramdown
