# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joe laskowski
email: joe.laskowski79@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a place for my thoughts and things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joelaskowski.me" # the base hostname & protocol for your site
twitter_username: thebiglaskowski
github_username:  thebiglaskowski
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Build settings
markdown: kramdown
